name: "Build"

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: '${{ vars.CACHIX_CACHE_NAME }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: nix-build
    - name: Save PR number
      if: github.event_name == 'pull_request'
      run: echo ${{ github.event.number }} > .github/pr
    - uses: actions/upload-artifact@v2
      if: github.event_name == 'pull_request'
      with:
        name: pr
        path: |
          result
          .github/pr
    - uses: actions/upload-artifact@v2
      if: github.event_name == 'push'
      with:
        name: build
        path: result
