name: "CI"
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: nix-dev
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: nix-build
    - name: Linkcheck
      run: nix-shell --run "make linkcheck"
    - name: Run code block tests
      run: nix-shell --run "./run_code_block_tests.sh"
    - name: Publish to nix.dev
      if: github.event_name == 'push'
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        directory: ./result
    - name: Publish preview
      id: preview
      if: github.event_name == 'pull_request_target'
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        directory: ./result
        branch: pr-${{ github.event.pull_request.number }}
    - name: Create comment on PR
      uses: peter-evans/create-or-update-comment@v2
      if: github.event_name == 'pull_request_target'
      with:
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: |
          <table>
            <tr>
              <td><b>Latest commit:</b></td>
              <td><code>${{ github.event.pull_request.head.sha }}</code></td>
            <tr>
            <tr>
              <td><b>Preview URL:</b></td>
              <td><a href="${{ steps.preview.outputs.url }}>${{ steps.preview.outputs.url }}</td>
          </table>
