name: "Deploy"

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  production:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Publish to nix.dev
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          directory: ./result
          branch: main
